name: CI

on:
  - push
  - pull_request

jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Install Rubocop
        run: bundle
      - name: Check Code
        run: bundle exec rubocop
  
  test:
    name: Rspec-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
      - run: bundle exec rake rspec
